build_the_car:
  stage: build
  script:
    - mkdir build
    - cd build
    - touch car.txt
    - echo "First ci cd codes." > car.txt
    - echo "my second line ? " >> car.txt
    - echo "thrd line too may be ??" >> car.txt
  tags:
    - my-self-hosted-runner
